services:
  app:
    image: anugrahfitra/web-hextris-image
    container_name: web-hextris
    build: .
    ports:
      - "8010:80"
    volumes:
      - nginx-vol:/var/www/html/

volumes:
  nginx-vol:
root@server-01-fitra:/home/azureuser/hextris# cat deployment-hextris.yaml 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx
  labels:
    app: deployment-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deployment-nginx
  template:
    metadata:
      labels:
        app: deployment-nginx
    spec:
      containers:
      - name: web-hextris
        image: anugrahfitra/web-hextris-image
        ports:
        - containerPort: 80